#! /usr/bin/python

from optparse import OptionParser
import os.path
import subprocess

# Main task runner
# for now a dumb wrapper
# Look at tasks in the tasks/ folder

task_folder = 'tasks'

def main():
    parser = OptionParser()
    (options, args) = parser.parse_args()

    # if no params - list all available tasks
    if args == []:
        print "Listing all tasks. WIP"
        return

    print "Running " + " ".join(args)
    task_path = reduce(lambda x,y: os.path.join(x, y), args, task_folder)
    # check validity of task
    if os.path.isfile(task_path):
        print "Task found."
    else:
        print "Task unavailable. Have a nice day."
        return

    print "Procceding to deploy script..."
    task_path = "./" + task_path 
    subprocess.call(task_path)
    print "Task completed. Have a nice day."

if __name__ == "__main__":
    main()

