#! /usr/bin/python

from optparse import OptionParser
import os.path
import subprocess
import os

# Main task runner
# for now a dumb wrapper
# Look at tasks in the tasks/ folder

task_folder = 'tasks'

# the parameter dictionary
settings = {}

def load_dotfile():
    """ Read config from dotfile ".butler".

    Load required parameters.
    """

    username = os.getenv("USER")

    f = open("/home/{0}/.butler".format(username)).read()
    lines = f.split("\n")

    lines = filter(lambda x: x != "", lines)
    lines = filter(lambda x: x.strip(" ")[0] != '#', lines)

    # there should be key value pairs
    settings_str = map(lambda x: x.strip(" ").split(" "), lines)
    global settings
    for s in settings_str:
        settings[s[0]]= s[1]
        
def main():
    parser = OptionParser()
    (options, args) = parser.parse_args()

    # load user specific config file
    load_dotfile()

    # go to the butler directory
    os.chdir(settings['BUTLER_DIR'])

    # if no params - list all available tasks
    if args == []:
        print "Listing all tasks. WIP"
        return

    print "Running " + " ".join(args)
    task_path = reduce(lambda x,y: os.path.join(x, y), args, task_folder)
    # check validity of task
    if os.path.isfile(task_path):
        print "Task found."
    else:
        print "Task unavailable. Have a nice day."
        return

    print "Procceding to deploy script..."
    task_path = "./" + task_path 
    subprocess.call(task_path)
    print "Task completed. Have a nice day."

if __name__ == "__main__":
    main()

