#!/bin/bash

# Setup emacs

# setup work dir
WORKSPACE="workspace"
echo "Setting up workspace"
if [ -d $WORKSPACE ];
then
  echo "Using existing folder: $WORKSPACE"
else
  echo "Creating workspace folder: $WORKSPACE"
  mkdir $WORKSPACE
fi

# SETTING UP EMACS

# helpers
command_exists () {
    command -v "$1" > /dev/null 2>&1
}

# see if emacs is installed

echo "*******************"
if command_exists emacs ; then
  echo "emacs available"
else
  echo "emacs not installed."
  echo "Installing emacs..."
  sudo apt-get install -y emacs
fi

# get corresponding module 
# here, my own dotfiles repo
MODULE="dotfiles"
URL="https://github.com/ChanderG/dotfiles"

if [ -d $WORKSPACE/$MODULE ]; then
  echo "Module already loaded.Pulling the latest version..."
  cd $WORKSPACE/$MODULE 
  git pull
  cd - > /dev/null
else
  echo "Obtaining relevant module..."
  git clone $URL $WORKSPACE/$MODULE
  echo "Module obtained"
fi

if [ -f ~/.emacs ]; then
  echo "~/.emacs already exists."
  echo "Cannot proceed with setup."
else
  ln -s `pwd`/$WORKSPACE/$MODULE/.emacs ~/.emacs
  echo "Setup emacs .Close emacs (if open) for changes to be reflected."
fi
