#!/bin/bash

# Setup tmux

# setup work dir
WORKSPACE="workspace"
echo "Setting up workspace"
if [ -d $WORKSPACE ];
then
  echo "Using existing folder: $WORKSPACE"
else
  echo "Creating workspace folder: $WORKSPACE"
  mkdir $WORKSPACE
fi

# SETTING UP TMUX

# helpers
command_exists () {
    command -v "$1" > /dev/null 2>&1
}

# see if tmux is installed

echo "*******************"
if command_exists tmux ; then
  echo "tmux available"
else
  echo "tmux not installed."
  echo "Installing tmux..."
  sudo apt-get install -y tmux
fi

# get corresponding module 
# here, my own dotfiles repo
MODULE="dotfiles"
URL="https://github.com/ChanderG/dotfiles"

if [ -d $WORKSPACE/$MODULE ]; then
  echo "Module already loaded.Pulling the latest version..."
  cd $WORKSPACE/$MODULE 
  git pull
  cd - > /dev/null
else
  echo "Obtaining relevant module..."
  git clone $URL $WORKSPACE/$MODULE
  echo "Module obtained"
fi

if [ -f ~/.tmux.conf ]; then
  echo "~/.tmux.conf already exists."
  echo "Cannot proceed with setup."
else
  ln -s `pwd`/$WORKSPACE/$MODULE/.tmux.conf ~/.tmux.conf
  echo "Setup tmux conf. Close all tmux sessions (if any) for changes to be reflected."
fi
