#! /bin/bash

# setup vim

# setup work dir
WORKSPACE="workspace"
echo "Setting up workspace"
if [ -d $WORKSPACE ];
then
  echo "Using existing folder: $WORKSPACE"
else
  echo "Creating workspace folder: $WORKSPACE"
  mkdir $WORKSPACE
fi

# install the required version of vim directly
echo "Installing vim-nox (scripting langauge compatibility)..."
sudo apt-get install -y vim-nox

# get corresponding module 
# here, my own vimrc repo
MODULE="vimrc"
URL="https://github.com/ChanderG/vimrc"

if [ -d $WORKSPACE/$MODULE ]; then
  echo "Module already loaded.Pulling the latest version..."
  cd $WORKSPACE/$MODULE 
  git pull
  cd - > /dev/null
else
  echo "Obtaining relevant module..."
  git clone $URL $WORKSPACE/$MODULE
  echo "Module obtained"
fi

if [ -f ~/.vimrc ]; then
  echo "~/.vimrc already exists."
  echo "Cannot proceed with setup."
else
  ln -s `pwd`/$WORKSPACE/$MODULE/.vimrc ~/.vimrc
  echo "Setup vimrc. "
fi

# now taking care of all plugins
# using Vundle

echo "Installing Vundle"
if [ -d ~/.vim/bundle/Vundle.vim ]; then
  echo "Vundle already loaded.Pulling the latest version..."
  cd ~/.vim/bundle/Vundle.vim
  git pull
  cd - > /dev/null
else
  echo "Obtaining Vundle..."
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  echo "Done."
fi

# install plugins
echo "Installing plugins..."
vim +PluginInstall +qall
echo "Installed plugins."
